config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  resources :rooms, only: [:create, :show], param: :token do
    resources :players, only: [:new, :create]
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :player

  validates :body, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :room_players
  has_many :rooms, through: :room_players

  before_create :set_punchline

  scope :online, -> { where(online: true) }

  def increment_score!
    update(score: score + 1)
  end

  def online!
    reload
    update(online: true)
  end

  def add_to(room)
    room_players.create(room: room)
  end

  def offline!
    reload
    update(online: false)
  end

  def ready!
    reload
    update(ready: true)
  end

  def not_ready!
    update(ready: false)
  end

  private

  def set_punchline
    self.punchline = [
      '“Je suis chaud bouillant“',
      '“Je suis pas pour faire tourner les serviettes“',
      '“Bande de rigolos“',
      '“Saint Etienne 💚 > Lyon“',
      '“Qu‘est ce que je fous là ⁇“',
      '“quiéyeière ér ér ér???“',
      '“Muscle ton jeu Robert !“',
      '“PARCE QUE C‘EST NOTRE PROOOJJJJETTT !!!“',
      '“The yes needs the no to win against the no 🤔“',
      '“Hakuna Matata“',
      '“Tu bluffes Martoni 🤥“',
    ].sample
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :room_players, dependent: :destroy
  has_many :players, through: :room_players
  belongs_to :dealer, optional: true, class_name: 'Player'

  before_create :set_token

  def start!
    dealer_id = players.pluck(:id).sample
    update(started: true, dealer_id: dealer_id)
  end

  def increment_score_for(id)
    players.find(id).increment_score!
  end

  def toggle_play!
    update(playing: !playing)
  end

  def stop!
    players.each(&:not_ready!)
    update(playing: false, song_id: nil)
  end

  def set_song(id)
    players.each(&:not_ready!)
    update(song_id: id)
  end

  def everyone_ready?
    players.pluck(:ready).all?(true)
  end

  def update_dealer
    sorted_ids = players.online.order(:id).pluck(:id)
    index = sorted_ids.index { |id| id == dealer.id }
    new_dealer_id = ((sorted_ids.length > index + 1) ? sorted_ids[index + 1] : sorted_ids[0])
    update(dealer_id: new_dealer_id)
  end

  private

  def set_token
    self.token = DateTime.now.strftime("%Y%m%d%H%M%S%L").to_i.to_s(36)
  end
end

app/models/room_player.rb
class RoomPlayer < ApplicationRecord
  belongs_to :room
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    Player.find(session[:player_id])
  rescue ActiveRecord::RecordNotFound => e
    nil
  end
  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_room

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      save_id_in_session
      redirect_to room_path(@room.token)
    else
      render :new
    end
  end

  private

  def set_room
    @room = Room.find_by(token: params[:room_token])
  end

  def player_params
    params
      .require(:player)
      .permit(:username)
      .merge(rooms: [@room])
  end

  def save_id_in_session
    session[:player_id] = @player.id
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_username, only: :show

  def create
    @room = Room.new

    if @room.save
      redirect_to new_room_player_path(@room.token)
    else
      redirect_to root_path
    end
  end

  def show
    @room = Room.find_by(token: params[:token])

    if current_user.blank?
      redirect_to new_room_player_path(@room.token) unless current_user.present?
    else
      attach_player_to_room unless current_user.rooms.include?(@room)
    end
  end

  def join
    @room = Room.find_by(token: params[:token])
  end

  private

  def set_username
    session[:username] = params[:user][:username] if params[:user].present?
  end

  def attach_player_to_room
    current_user.add_to(@room)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlindTestParty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body class="<%= params[:debug].present? ? 'debug': '' %>">
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center text-4xl my-12">Des paillettes dans vos vie pendant le confinement ✨🚀🦠</h1>

<div class="text-center mt-24">
  <%= link_to 'Yallah 🕺❤️', rooms_path, method: :post, class: 'button'  %>
</div>

app/views/players/new.html.erb
<div class="text-center mt-32">
  <%= simple_form_for([@room, @player], url: room_players_path(@room.token)) do |f| %>
    <div class="mb-8">
      <%= f.input :username, label: "C'est quoi ton blaz ?", placeholder: 'Fatal', label_html: { class: 'text-4xl mb-4' }, input_html: { class: 'text-2xl' } %>
    </div>
    <%= f.submit "J'suis chaud, j'vais tout péter 🥇", class: 'button' %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="flex">
  <div class="flex-grow">
    <h1 class="text-center text-4xl my-12">It's gonna be..... Wait for it !!! Corodinary 🦇</h1>

    <p class="sharable-link text-center text-blue-600">
      Fais tourner a tes potes, ils vont arriver 🚀 => <%= room_url(@room.token) %>
    </p>

    <p class="who-is-dealer hidden text-center text-3xl">
      C'est <span></span> qui deal 🦦 🎧 !
    </p>

    <div class="youtube-link mx-auto text-white hidden text-center">
      <label class="text-2xl">C'est toi le dealer, fait péter ton lien youtube</label>
      <div class="flex">
        <input id="songInput" class="flex-grow text-black" type="text" placeholder="Rick Astley - Never Gonna Give You Up">
        <button id="submitSong" class="border border-black border-solid px-4 py-2 hover:bg-gray-200 mx-4">C'est bon 🤓</button>
      </div>
      <p class="loading hidden text-2xl">On attend que ca charge chez tout le monde 😴</p>
      <p class="toggle hidden justify-center text-2xl flex">
        <button id="togglePlay" class="border my-8 border-blue-900 bg-white text-blue-900 border-solid px-4 py-2 hover:bg-gray-200 mx-4"></button>
        <button id="next" class="border my-8 ml-4 border-black border-solid px-4 py-2 hover:bg-gray-200 mx-4">Next, personne trouve 🐠</button>
      </p>
    </div>

    <div class="flex justify-center items-center">
      <button id="start" class="<%= 'hidden' if @room.started? %> border border-black border-solid px-4 py-2 mt-8 hover:bg-gray-200 mx-4">Commencer 🎬</button>
    </div>

    <div id="participants" class="mx-auto mt-8" data-token="<%= @room.token %>" data-current-user="<%= current_user.id %>"></div>
    <video id="plyr"></video>
  </div>

  <div id="chat" class="flex sticky top-0 shadow-lg border-left border-solid border-black flex-col bg-white h-screen">
    <form id="chatForm">
      <input type="text" placeholder="Ton message" class="w-full" id="messageInput" autocomplete="off">
      <input type="submit" class="hidden">
    </form>
    <div class="messages p-3 flex-grow overflow-scroll"></div>
  </div>
</div>